#ifndef PLUGINSETTINGSWIDGET_GLOBAL_H
#define PLUGINSETTINGSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINSETTINGSWIDGET_LIB
# define PLUGINSETTINGSWIDGET_EXPORT Q_DECL_EXPORT
#else
# define PLUGINSETTINGSWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINSETTINGSWIDGET_GLOBAL_H
